services:
  - type: web
    name: jumpandlearn-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jumpandlearn
          property: connectionString

databases:
  - name: jumpandlearn
    databaseName: jumpandlearn
    user: jumpandlearn_user
